name: Get Pubslic IP

on:
  push:
    branches:
      - main

jobs:
  set-env:
    name: Fetch Public IP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get Public IP
        run: dig +short myip.opendns.com @resolver1.opendns.com
        id: get-ip
      - name: Run Python Script
        run: python script.py
        env:
          CLOUD_SDK_AK: ${{ secrets.MY_SECRET_KEY }}
          CLOUD_SDK_SK: ${{ secrets.ANOTHER_SECRET }}
          IP_ADDRESS: ${{ steps.get-ip.outputs.stdout }}
          
