name: Get Pubslic IP

on:
  push:
    branches:
      - Mastin

jobs:
  set-env:
    name: set-env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: get SDK
        run: pip install huaweicloudsdkvpc
      - name: Get Public IP
        id: public-ip
        run:  echo "ip_address=$(dig +short myip.opendns.com @resolver1.opendns.com)\n" >> $GITHUB_OUTPUT
        
        
      - name: Run Python Script
        run: python script.py
        env:
          CLOUD_SDK_AK: ${{ secrets.CLOUD_SDK_AK }}
          CLOUD_SDK_SK: ${{ secrets.CLOUD_SDK_SK }}
          IP_ADDRESS:  ${{ steps.public_ip.outputs.ip_address }}
          SG_ID: ${{ secrets.SG_ID }}

      - name: Set up SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Clone Repository on Host
        run: ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'git clone <repository-url> /path/to/repository'
      - name: SSH into Host and Execute Commands
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'cd /root/actionstest && \
                         go mod download && \
                         go build -o main . && \
                         ./main'
          
