name: Get Pzubslic IP

on:
  push:
    branches:
      - main

jobs:
  set-env:
    name: set-env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: get SDK
        run: pip install huaweicloudsdkvpc
      - name: Get Public IP
        id: public-ip
        run:  echo "ip_address=$(dig +short myip.opendns.com @resolver1.opendns.com)\n" >> $GITHUB_OUTPUT
        
        
      - name: Run Python Script
        run: python script.py
        env:
          CLOUD_SDK_AK: ${{ secrets.CLOUD_SDK_AK }}
          CLOUD_SDK_SK: ${{ secrets.CLOUD_SDK_SK }}
          IP_ADDRESS:  ${{ steps.public_ip.outputs.ip_address }}
          SG_ID: ${{ secrets.SG_ID }}

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_ACTIONS }}

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: sudo apt-get update && sudo apt-get install -y golang
          
