name: Get Pubslic IP

on:
  push:
    branches:
      - main

jobs:
  get-ip:
    name: Fetch Public IP
    runs-on: ubuntu-latest
    steps:
      - name: Get Public IP
        run: python --version
